language: php
install:
- composer install
php:
- 5.6
- 5.5
- hhvm
script:
- vendor/bin/phpunit
- vendor/bin/phpcs --standard=PSR2 src tests
notifications:
  slack:
    secure: lWuAu0XNT/0+3kfVOnt66+H5r6dddeyEzajcfspvNG3LOPMrsTidpO5LHjeh24tOdMMOpwQpwodySM+nR+EhxOlXpbjc2rv0zCrs7rPlfkd/dHskGgHqV3rVHtGyjXon5RGr0f2yyo5XdhECFVYissGlqji82ar605oALNzzkDw=
